@startuml
'https://plantuml.com/sequence-diagram

/'autonumber'/
skinparam actorStyle awesome
skinparam roundcorner 15

skinparam sequence {

    ArrowColor DeepSkyBlue
    ActorBorderColor #333
    LifeLineBorderColor gray
    LifeLineBackgroundColor #A9DCDF

    ParticipantBorderColor #333
    ParticipantBackgroundColor white
    ParticipantFontName Aapex
    ParticipantFontSize 13
    ParticipantFontColor #333

    ActorBackgroundColor white
    ActorFontColor #333
    ActorFontSize 13
    ActorFontName Aapex

    GroupBorderColor #888
    GroupFontName Aapex
    GroupFontColor #333

}


actor       Bruker        as User
participant Mindmap     as Mindmap
participant MindmapNode as Node
participant Subnode as Sub
participant SubSubnode as Subsub


Mindmap -> Node: Genererer hovednoden med\nmindmapData som prop

Node -> Sub: Generer barn og sender\nchildren[i] som prop



alt Hvis node har subnoder

    Sub -> Subsub: Generer barn og sender\nchildren[i] som prop

else Hvis node ikke har subnoder

    Sub -> Sub: Generer en\nMindmapEdge
    Sub -> Sub: Generer en\nNodeText


end
Node <-- Sub: Renderer og\nReturnerer (Callback))
Node -> Node: Generer en\nMindmapEdge
Node -> Node: Generer en\nNodeText

Mindmap <-- Node: Renderer og\nReturnerer (Callback))

User <-- Mindmap: Renderer og\nviser tankekart

@enduml