@startuml
left to right direction
skinparam class {
    BackgroundColor white
    ArrowColor #555
    BorderColor #333333
}

skinparam roundcorner 15

class "   Mindmap   " as mindmap <<(C, 88bbdd) component>> {
    ==state==
    # projectTemplates
    # existingProjects
    # mindmapData
    ==methods==
    loadTemplatesAndProjects()
    createNewProject()
    loadProject()
    handleSelected()
    updateMainNode()

}

class "   MindmapNode   " as mmNode <<(C, 88bbdd) component>> {
    ==props==
    # node
    # parent
    # reportToParent
    # handleSelected
    # index
    # selectedNodeId
    ==Methods==
    createNewNode()
    handlePlusButtonClick()
    updateChild()

}

class "   NodeText   " as mmText<<(C, 88bbdd) component>> {
    ==props==
    # node

}

class "   MindmapEdge   " as mmEdge<<(C, 88bbdd) component>> {
    ==props==
    # x1
    # y1
    # x2
    # y2

}

class "   ZoomPanWrapper   " as zoompan <<(C, 88bbdd) component>> {
    D3 logic
}

class "   DragWrapper   " as drag <<(C, 88bbdd) component>> {
    D3 logic
}


mindmap --> mmNode
mindmap -> zoompan
mmNode o-- mmNode
mmNode --> mmText
mmNode --> mmEdge
mmNode -> drag
@enduml