@startuml
'https://plantuml.com/sequence-diagram

/'autonumber'/
skinparam actorStyle awesome
skinparam roundcorner 15

skinparam sequence {

    ArrowColor DeepSkyBlue
    ActorBorderColor #333
    LifeLineBorderColor gray
    LifeLineBackgroundColor #A9DCDF

    ParticipantBorderColor #333
    ParticipantBackgroundColor white
    ParticipantFontName Aapex
    ParticipantFontSize 13
    ParticipantFontColor #333

    ActorBackgroundColor white
    ActorFontColor #333
    ActorFontSize 13
    ActorFontName Aapex

    GroupBorderColor #888
    GroupFontName Aapex
    GroupFontColor #333

}


actor       Bruker        as User
participant Mindmap     as Mindmap
participant MindmapNode as Node
participant MindmapEdge as Edge


User -> Node: Trykker på legg-til-knapp på node
Node -> Node: Kaller ny node funskjoner:\nplusButtonClicked()\ncreateNode()
Node -> Edge:
Node <-- Node: Rapporterer opp til forelder\nsom rapporetere til sin forelder\nhelt til hovednoden foår beskjed
Mindmap <-- Node: Hovednode rapporterer\n til Mindmap


alt Hvis data er oppdatert

    Node -> Edge: Sender ned\noppdaterte properties
    Node -> Node: Re-render

else Hvis ikke oppdatert

    Node -> Node: Inget skjer

end


Mindmap <-- Node: Returnerer (Callback))

User <-- Mindmap: Oppdatert tankekart

@enduml