@startuml
'https://plantuml.com/class-diagram

class Mindmap << (C,red) container>> {
    ==state==
    nodes
    ==props==
}

class MindmapNode << (C,blue) component>> {
     ==props==
     nodeProperties
     parent
     edge

     == Functions ==
     createNewNode

}

class MindmapEdge << (C,blue) component>> {
     ==props==
     nodeProperties
     parent
     edge
}

@enduml